name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: 3.1.300

      - uses: actions/checkout@v2

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet publish -c Release

      - name: Zip Release
        run: Compress-Archive -Path .\Bin\Release\netcoreapp3.1\publish\* -DestinationPath .\Release.zip

      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: build_${{ github.run_number }}
          release_name: Trunk ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload a Release Asset
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_urL: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Release.zip
          asset_name: Release.zip
          asset_content_type: application/zip
